Repository ConstantineFSA/Constantine-Shopper, pull requests merged in 2023-03, with the labels that each got.

#34 Edit user form
  client/features/editUserForm/editUserForm.js
  client/features/user/User.js
  client/features/user/userSlice.js
  public/bundle.js
  public/bundle.js.map
  server/api/users.js
Labels: enhancement

#36 Users view
  client/features/editUserForm/EditUser.js
  client/features/styles/User.css
  client/features/styles/Users.css
  client/features/user/User.js
  client/features/user/userSlice.js
  client/features/users/Users.js
  client/features/users/usersSlice.js
  mock_user_data.js
  package-lock.json
  package.json
  public/assets/.DS_Store
  public/assets/images/.DS_Store
  public/assets/images/default_user_img.svg
  server/api/users.js
  server/db/models/User.js
  webpack.config.js
Labels: enhancement, feature update

#39 Create EditProductForm, route, and slice, edit SingleProduct component
  client/features/singleProduct/EditProductForm.js
  client/features/singleProduct/SingleProduct.js
  client/features/singleProduct/singleProductSlice.js
  server/api/singleProduct.js
Labels: enhancement, feature update

#44 Add delete functionality for single product view, add cart button
  client/features/singleProduct/SingleProduct.js
  client/features/singleProduct/singleProductSlice.js
  server/api/singleProduct.js
Labels: enhancement, feature update

#43 Add basic pagination to the all users view. Further tweaking could be…
  client/features/pagination/Pagination.js
  client/features/styles/Pagination.css
  client/features/users/Users.js
Labels: enhancement

#47 Implement isAdmin feature to single user view/my account view.
  client/features/editUserForm/EditUser.js
  client/features/styles/User.css
  client/features/styles/Users.css
  client/features/user/User.js
Labels: feature update

#55 Made changes to seed file. Adjust model associations.
  client/app/AppRoutes.js
  client/app/store.js
  client/features/cart/Cart.js
  client/features/cart/cartSlice.js
  client/features/navbar/Navbar.js
  mock_cart_data.js
  script/seed.js
  server/api/users.js
  server/db/index.js
Labels: enhancement, feature update

#59 New cart branch
  client/app/AppRoutes.js
  client/features/auth/authSlice.js
  client/features/cart/Cart.js
  client/features/cart/cartSlice.js
  client/features/guestCart/GuestCart.js
  client/features/navbar/Navbar.js
  client/features/products/Products.js
  client/features/products/productsSlice.js
  client/features/singleProduct/SingleProduct.js
  client/features/singleProduct/singleProductSlice.js
  client/features/styles/Cart.css
  script/seed.js
  server/api/singleProduct.js
  server/api/users.js
Labels: enhancement, help wanted, feature update

#63 Update products data for seed file
  mock_product_data.js
Labels: feature update

#65 Add editing cart functionality, remove navigate to cart for products
  client/features/cart/Cart.js
  client/features/products/Products.js
  client/features/singleProduct/SingleProduct.js
Labels: enhancement, feature update

#70 Edit cart
  client/features/cart/Cart.js
  client/features/cart/cartSlice.js
  server/api/products.js
  server/api/users.js
Labels: feature update

#71 Edit cart
  client/features/cart/Cart.js
  client/features/cart/cartSlice.js
  server/api/users.js
Labels: feature update

#73 Checkout
  client/features/cart/CheckoutForm.js
  client/features/cart/Payment.js
  client/features/cart/cartSlice.js
  mock_cart_data.js
  server/api/users.js
Labels: feature update
